services:
  # Our database management system
  db:
    environment:
      MARIADB_USER: &dbuser todo
      MARIADB_PASSWORD: &dbpass todosecret
      MARIADB_ROOT_PASSWORD: iamroot
      MARIADB_DATABASE: &dbname videos

  # Our microservice, built with './gradlew dockerBuild'
  videos:
    environment:
      DB_USER: *dbuser
      DB_PASSWORD: *dbpass
      DB_NAME: *dbname
