name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  VM_Build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout if no cache
      if: steps.cache-images.outputs.cache-hit != 'true'
      uses: actions/checkout@v3

    - name: build VM if no cache
      if: steps.cache-images.outputs.cache-hit != 'true'
      run: | 
        cd ${GITHUB_WORKSPACE}/Microservices/video-microservice
        ./gradlew dockerBuild

    - name: Save images to cache
      id: cache-images-save
      if: steps.cache-images.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          ./
        key: ${{ steps.cache-images.outputs.cache-primary-key }}

  THM_Build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout if no cache
      if: steps.cache-images.outputs.cache-hit != 'true'
      uses: actions/checkout@v3

    - name: build THM if no cache
      if: steps.cache-images.outputs.cache-hit != 'true'
      run: | 
        cd ${GITHUB_WORKSPACE}/Microservices/trending-hashtags-microservice
        ./gradlew dockerBuild

    - name: Save images to cache
      id: cache-images-save
      if: steps.cache-images.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          ./

        key: ${{ steps.cache-images.outputs.cache-primary-key }}

  SM_Build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout if no cache
      if: steps.cache-images.outputs.cache-hit != 'true'
      uses: actions/checkout@v3

    - name: build SM if no cache
      if: steps.cache-images.outputs.cache-hit != 'true'
      run: | 
        cd ${GITHUB_WORKSPACE}/Microservices/subscription-microservice
        ./gradlew dockerBuild

    - name: Save images to cache
      id: cache-images-save
      if: steps.cache-images.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          ./
        key: ${{ runner.os }}-image3

  Test:
    runs-on: ubuntu-latest
    needs: [VM_Build, THM_Build, SM_Build]
    steps:
    - name: Restore cached images
      id: cache-images
      uses: actions/cache/restore@v4
      with:
        path: |
          ./
        key:   |
          ${{ runner.os }}-image1
          ${{ runner.os }}-image2
          ${{ runner.os }}-image3